
title: Diana Lamriben
email: hello@danyalamriben.org
description: "Diana Lamriben is a Design Researcher located in Central Ohio specializing in user research, design thinking, and information architecture"
baseurl: "/MVP"
url: "https://danyalamriben.org"
github_username:  danyalamriben

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed

sass:
    sass_dir: _sass

collections:
  projects:
    output: true
